### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by jdejoode** [HybirdCorp/creme_crm#343]
Thanks for a great project. I like the tools you have chosen and would love to contribute. Do you think you could release the code under the more generally used MIT license? Thanks!

**Comment by genglert** [comment]
Hi,

- we are still using at least one GPL component, so even if we wanted, we could not change to a not *GPL license yet.
- when a module could be useful for other projects & does not depend on other Creme's modules, we use a MIT(-like) license (see files in creme/creme_core/utils/ for example).

Creme is a final/complete application, not a library, so its license won't be generally a problem for other free/open-source software (because of license conflict between several libraries for example).

We chose AGPL to not provide a out-of-the-box solution for people which want to deploy closed SAS ; you can still use Creme in a commercial way of course, you just have to provide the source code to your users (if they ask you). We do not sell a commercial/proprietary version of Creme (with exclusive features which are not in the free version) ; there is only one version, the free/open-source one. Our customers pay us to develop specific code, to host their instance, to train them, but they are never locked because they cannot have (& copy/modify/...) the source code.
